<?php

namespace Database\Seeders;

use App\Models\PaymentMethod;
use Illuminate\Database\Seeder;

class PaymentMethodSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $paymentMethods = [
            [
                'payment_method_id' => '6',
                'payment_method_ar' => 'مدى',
                'payment_method_en' => 'MADA',
                'payment_method_code' => 'md',
                'is_direct_payment' => false,
                'service_charge' => 0.00,
                'total_amount' => 0.00,
                'currency_iso' => 'KWD',
                'image_url' => 'https://demo.myfatoorah.com/imgs/payment-methods/md.png',
                'is_embedded_supported' => true,
                'payment_currency_iso' => 'SAR',
                'status' => 'inactive',
                'is_ios_supported' => true,
                'is_android_supported' => true,
                'is_web_supported' => true,
            ],
            [
                'payment_method_id' => '11',
                'payment_method_ar' => 'أبل الدفع',
                'payment_method_en' => 'Apple Pay',
                'payment_method_code' => 'ap',
                'is_direct_payment' => false,
                'service_charge' => 0.00,
                'total_amount' => 0.00,
                'currency_iso' => 'KWD',
                'image_url' => 'https://demo.myfatoorah.com/imgs/payment-methods/ap.png',
                'is_embedded_supported' => true,
                'payment_currency_iso' => 'KWD',
                'status' => 'active',
                'is_ios_supported' => true,
                'is_android_supported' => false,
                'is_web_supported' => false,
            ],
            [
                'payment_method_id' => '2',
                'payment_method_ar' => 'فيزا / ماستر',
                'payment_method_en' => 'VISA/MASTER',
                'payment_method_code' => 'vm',
                'is_direct_payment' => false,
                'service_charge' => 0.00,
                'total_amount' => 0.00,
                'currency_iso' => 'KWD',
                'image_url' => 'https://demo.myfatoorah.com/imgs/payment-methods/vm.png',
                'is_embedded_supported' => true,
                'payment_currency_iso' => 'KWD',
                'status' => 'active',
                'is_ios_supported' => true,
                'is_android_supported' => true,
                'is_web_supported' => true,
            ],
            [
                'payment_method_id' => '14',
                'payment_method_ar' => 'إس تي سي باي',
                'payment_method_en' => 'STC Pay',
                'payment_method_code' => 'stc',
                'is_direct_payment' => false,
                'service_charge' => 0.00,
                'total_amount' => 0.00,
                'currency_iso' => 'KWD',
                'image_url' => 'https://demo.myfatoorah.com/imgs/payment-methods/stc.png',
                'is_embedded_supported' => true,
                'payment_currency_iso' => 'SAR',
                'status' => 'inactive',
                'is_ios_supported' => true,
                'is_android_supported' => true,
                'is_web_supported' => true,
            ],
            [
                'payment_method_id' => '8',
                'payment_method_ar' => 'كروت الدفع المدنية (الإمارات)',
                'payment_method_en' => 'UAE Debit Cards',
                'payment_method_code' => 'uaecc',
                'is_direct_payment' => false,
                'service_charge' => 0.00,
                'total_amount' => 0.00,
                'currency_iso' => 'KWD',
                'image_url' => 'https://demo.myfatoorah.com/imgs/payment-methods/uaecc.png',
                'is_embedded_supported' => true,
                'payment_currency_iso' => 'AED',
                'status' => 'inactive',
                'is_ios_supported' => true,
                'is_android_supported' => true,
                'is_web_supported' => true,
            ],
            [
                'payment_method_id' => '9',
                'payment_method_ar' => 'Visa/Master Direct 3DS Flow',
                'payment_method_en' => 'Visa/Master Direct 3DS Flow',
                'payment_method_code' => 'vm',
                'is_direct_payment' => true,
                'service_charge' => 0.00,
                'total_amount' => 0.00,
                'currency_iso' => 'KWD',
                'image_url' => 'https://demo.myfatoorah.com/imgs/payment-methods/vm.png',
                'is_embedded_supported' => true,
                'payment_currency_iso' => 'KWD',
                'status' => 'inactive',
                'is_ios_supported' => true,
                'is_android_supported' => true,
                'is_web_supported' => true,
            ],
            [
                'payment_method_id' => '20',
                'payment_method_ar' => 'Visa/Master Direct',
                'payment_method_en' => 'Visa/Master Direct',
                'payment_method_code' => 'vm',
                'is_direct_payment' => true,
                'service_charge' => 0.00,
                'total_amount' => 0.00,
                'currency_iso' => 'KWD',
                'image_url' => 'https://demo.myfatoorah.com/imgs/payment-methods/vm.png',
                'is_embedded_supported' => true,
                'payment_currency_iso' => 'KWD',
                'status' => 'inactive',
                'is_ios_supported' => true,
                'is_android_supported' => true,
                'is_web_supported' => true,
            ],
            [
                'payment_method_id' => '3',
                'payment_method_ar' => 'اميكس',
                'payment_method_en' => 'AMEX',
                'payment_method_code' => 'ae',
                'is_direct_payment' => false,
                'service_charge' => 0.00,
                'total_amount' => 0.00,
                'currency_iso' => 'KWD',
                'image_url' => 'https://demo.myfatoorah.com/imgs/payment-methods/ae.png',
                'is_embedded_supported' => true,
                'payment_currency_iso' => 'USD',
                'status' => 'inactive',
                'is_ios_supported' => true,
                'is_android_supported' => true,
                'is_web_supported' => true,
            ],
            [
                'payment_method_id' => '32',
                'payment_method_ar' => 'جوجل للدفع',
                'payment_method_en' => 'GooglePay',
                'payment_method_code' => 'gp',
                'is_direct_payment' => false,
                'service_charge' => 0.00,
                'total_amount' => 0.00,
                'currency_iso' => 'KWD',
                'image_url' => 'https://demo.myfatoorah.com/imgs/payment-methods/gp.png',
                'is_embedded_supported' => true,
                'payment_currency_iso' => 'KWD',
                'status' => 'inactive',
                'is_ios_supported' => true,
                'is_android_supported' => true,
                'is_web_supported' => true,
            ],
            [
                'payment_method_id' => '5',
                'payment_method_ar' => 'بنفت',
                'payment_method_en' => 'Benefit',
                'payment_method_code' => 'b',
                'is_direct_payment' => false,
                'service_charge' => 0.00,
                'total_amount' => 0.00,
                'currency_iso' => 'KWD',
                'image_url' => 'https://demo.myfatoorah.com/imgs/payment-methods/b.png',
                'is_embedded_supported' => false,
                'payment_currency_iso' => 'BHD',
                'status' => 'inactive',
                'is_ios_supported' => true,
                'is_android_supported' => true,
                'is_web_supported' => true,
            ],
            [
                'payment_method_id' => '1',
                'payment_method_ar' => 'كي نت',
                'payment_method_en' => 'KNET',
                'payment_method_code' => 'kn',
                'is_direct_payment' => false,
                'service_charge' => 0.00,
                'total_amount' => 0.00,
                'currency_iso' => 'KWD',
                'image_url' => 'https://demo.myfatoorah.com/imgs/payment-methods/kn.png',
                'is_embedded_supported' => false,
                'payment_currency_iso' => 'KWD',
                'status' => 'active',
                'is_ios_supported' => true,
                'is_android_supported' => true,
                'is_web_supported' => true,
            ],
        ];

        foreach ($paymentMethods as $method) {
            PaymentMethod::updateOrCreate(
                ['payment_method_id' => $method['payment_method_id']],
                $method
            );
        }
    }
}